### ISSUE TITLE
RAND_MAX missing

### ISSUE THREAD

**Issue by TotallyGamerJet** [gotranspile/cxgo#14]
One of the c projects I am trying to convert uses RAND_MAX found in stdlib.h. I added it to the header in libs/stdlib.go and a go constant in runtime/libc/rand.go. I wondered if there is a way to make the header define equal to the go constant? This way future changes don't require two places to be updated.

**Comment by dennwc** [comment]
First, feel free to PR the change ;)

Second, there's no way to do that automatically for now, but I agree there should be. I did some preparations to auto-generate the header for function definitions, for example, so something similar should work for constants as well.

**Comment by TotallyGamerJet** [comment]
I think a new issue should be created for generating constants in headers so I’m going to close this issue
