### ISSUE TITLE
assigning string to [] of custom type fails

### ISSUE THREAD

**Issue by TotallyGamerJet** [gotranspile/cxgo#16]
```
#include <stdint.h>
int main() {
	typedef uint8_t  MYubyte;
	MYubyte vendor[] = "Robert Winkler";
	return 0;
}
```
This code compiles under gcc but it doesn't in cxgo. I get this error:
`Error: parsing failed: test.c:4:21: initializer for an object that has aggregate or union type shall be a brace-enclosed list of initializers for the elements or named members: array of MYubyte`

**Comment by dennwc** [comment]
If it says "parsing failed", it's worth opening an issue in [cznic/cc](https://gitlab.com/cznic/cc/), it's the parser that cxgo uses under the hood.

Thanks for isolating the cause!

**Comment by TotallyGamerJet** [comment]
So I've created an [issue](https://gitlab.com/cznic/cc/-/issues/122). It appears the issue lies in the fact that uint8_t is defined as unsigned __int8 which the parser doesn't recognize as being able to assign a string to it.

**Comment by TotallyGamerJet** [comment]
@dennwc with [this](https://gitlab.com/cznic/cc/-/commit/bbc9a11ec4656cc496548169eebf543954a40215) commit the code now generates. However, it generates invalid code. This is what I'm getting:
```
package main

import (
	"github.com/gotranspile/cxgo/runtime/libc"
	"os"
)

func main() {
	type MYubyte uint8
	var vendor [15]MYubyte = ([15]MYubyte)(libc.CString("Robert Winkler"))
	_ = vendor
	os.Exit(0)
}
```
The error is `Cannot convert an expression of the type '*byte' to the type '[15]MYubyte'`. I'm not sure what the proper translation is in order to find a fix. I know go 1.17 has a function unsafe.Slice(ptr, size) that could be used but that isn't out yet.

**Comment by dennwc** [comment]
I haven't considered it properly, but something like this should work:
```go
var vendor [15]MYubyte = [15]MYubyte([15]byte("Robert Winkler\x00"))
```
I don't remember if Go allows this kind of conversion, though.

**Comment by TotallyGamerJet** [comment]
Go doesn't allow conversion from string to byte arrays. It only allows string to byte slices. And slices can't be converted into arrays until [1.17](https://tip.golang.org/doc/go1.17) drops. I can only think of one possible way to get it to work which would be a copy:
```
var vendor [15]MYubyte
copy(vendor[:], []MYubyte("Robert Winkler"))
```
The benefit of this method is that it's clear and compatible with many versions of Go.
