### ISSUE TITLE
Define builtin types (size_t, ptrdiff_t, etc)

### ISSUE THREAD

**Issue by dennwc** [gotranspile/cxgo#33]
After discussion in https://gitlab.com/cznic/cc/-/issues/126 it's clear that cxgo must define types like `size_t`, `ptrdiff_t`, etc.

**Comment by TotallyGamerJet** [comment]
Isn’t it already defined in [stddef.h](https://github.com/gotranspile/cxgo/blob/121362ed1a0320f6d985f6db3d0ef570b2b96f7a/libs/stddef.go#L31)?

**Comment by dennwc** [comment]
They are, but the problem is that they actually need to be defined as builtins (without any includes).
