### ISSUE TITLE
unsafe.Add for arrays

### ISSUE THREAD

**Issue by TotallyGamerJet** [gotranspile/cxgo#34]
Do we want to start using `unsafe.Add` for arrays? It will make the code shorter and potentially easier to read. It would, however, require that we push the version of the compiler to 1.17 and all resulting code would use that version too.
Example:
```
var Ptr *int
Ptr = (*int)(unsafe.Pointer(uintptr(unsafe.Pointer(Ptr)) + uintptr(Len)))
```
Now becomes:
```
var Ptr *int
Ptr = (*int)(unsafe.Add(unsafe.Pointer(Ptr)), Len)
```

**Comment by dennwc** [comment]
Definitely! But as you mentioned, I would either prefer to wait a bit, or add an option to `cxgo.yml` to use old behavior.

**Comment by dennwc** [comment]
The time has come! I think it's safe to move on without adding it to options. Code definitely looks better with it.
