### ISSUE TITLE
panic in cxgo/convert.go

### ISSUE THREAD

**Issue by djadala** [gotranspile/cxgo#44]
panic: types.ArrayType{elem:(*types.namedType)(0xc0000e2f30), size:1, slice:false}."name" (test.c:14:10)
```c
struct s {
	const char *const name;		
};

static const struct s ss[] = {
	{NULL  },	
};


int
main(void) {

	if(!ss->name)
	 	return(-1);

 	return 0;
}	
```

**Comment by djadala** [comment]
changing  
```if(!ss->name)``` 
to
 ```if(!ss[0]->name)``` 
makes it compile

**Comment by dennwc** [comment]
Definitely a bug, thank you for reporting it!

**Comment by TotallyGamerJet** [comment]
After investigating this issue it appears to be a problem with CC and not CXGO. See this [issue](https://gitlab.com/cznic/cc/-/issues/130) I created. Currently waiting for a response.
