### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by g41797** [gotranspile/cxgo#61]
maze.io/x/math32 - looks broken
Downloading failed with timeout
It isn't the problem of cxgo per se ,
just FYI
Thanks

**Comment by dennwc** [comment]
Indeed, looks like the server on that domain no longer responds. I will make a copy of that repo in the following days :+1:

**Comment by g41797** [comment]
As far as I understand, it's possible to use different math32 pkg:
https://github.com/chewxy/math32

It used within https://github.com/TotallyGamerJet/pgl/blob/main/portablegl.go
...
package pgl

import (
	"encoding/binary"
	_**"github.com/chewxy/math32"**_
	_**"github.com/gotranspile/cxgo/runtime/cmath"**_
	"math"
	"unsafe"
)
..........

**Comment by dennwc** [comment]
Good idea! Will use it instead.

In the meantime, you can add `replace` to `go.mod` to fix build:
```
replace maze.io/x/math32 => github.com/chewxy/math32
```

**Comment by g41797** [comment]
go install ***@***.***

go.mod:
...
replace maze.io/x/math32 => github.com/chewxy/math32 *v1.10.1*
....

go build

runtime/cmath/math.go:5:2: missing go.sum entry for module providing
package maze.io/x/math32 (imported by github.com/gotranspile/cxgo/runtime/cm
ath); to add:
       go get github.com/gotranspile/cxgo/runtime/cmath

Looks replace in mod isn't enough 😞

go mod tidy - didn't help

cleanup of cache and reinstall - the same result

i am not familiar with modules management in Go

Any ideas?

**Comment by dennwc** [comment]
Yeah, looks like this won't work. I would hope for `go mod tidy` to fix it, but looks like it still needs some info about base repo.

I'll try to fix it sooner then.

**Comment by g41797** [comment]
I think cxgo itself doesn't use math32 (only runtime)
what is the reason for failure during build?

**Comment by dennwc** [comment]
It still uses it to type check generated code. Basically it takes signatures from it to generate (virtual) C headers. But yeah, in this case it could be avoided,since signatures are well-known.

**Comment by g41797** [comment]
Is it a good first issue?

**Comment by dennwc** [comment]
Definitely!

**Comment by g41797** [comment]
how to proceed?

**Comment by dennwc** [comment]
Fixed. Should work now.
