### ISSUE TITLE
panic for typedef of void

### ISSUE THREAD

**Issue by g41797** [gotranspile/cxgo#63]
From `struct_FILE.h`:
```
#ifndef _IO_lock_t_defined
typedef void _IO_lock_t;
#endif
```

Result:
2023/04/08 07:47:14 ipptool.c
panic: TODO: typedef of void? /usr/include/bits/types/struct_FILE.h:43:14

I cannot define _IO_lock_t_defined via yml, because 
"...# error "_IO_lock_t_defined should only be defined when building libc itself"

convert.go:
```
					if vt == nil {
						panic("TODO: typedef of void? " + id.Position().String())
					}
```

Is there workaround for this case?

**Comment by g41797** [comment]
'typedef void' may be used only for pointers:

_IO_lock_t *_lock == void* _lock

for any usage cast to real struct should be done in implementation

Possible solution may be to think about typedef **_void_** as typedef **_char_**
(alias for typedefvoid  in yml ???)

**Comment by g41797** [comment]
Checked this idea in local branch:
.....
			if isTypedef && vt == nil {
				vt = types.IntT(1)
			}
....................

at least no panic

**Comment by g41797** [comment]
there are two open issues #63&64 for typedef void
I'd like to delete #64 , revert PR and supply new code in context of #63

How to proceed?

**Comment by dennwc** [comment]
You can either close #64 and create a new one, or force-push new code to the same branch.

**Comment by g41797** [comment]
#64 closed
Created new PR #65

**Comment by dennwc** [comment]
Merged! Thank you for looking into it!

**Comment by g41797** [comment]
is there good-*second*-issue?

**Comment by dennwc** [comment]
#62 is a good one :+1: I will explain how to fix it.

**Comment by g41797** [comment]
great
please send me hints for the start

**Comment by g41797** [comment]
or add to  #62 <https://github.com/gotranspile/cxgo/issues/62>
thanks
