### ISSUE TITLE
Proposal: Separate C header from go code within bundle of well-known headers

### ISSUE THREAD

**Issue by g41797** [gotranspile/cxgo#66]
For the case C header is constant string:
1. RegisterLibrary uses header text without additions (windows.h/windows.go)
2. Header + Indents + etc

For 1. - Headers will be placed in dedicated folder and automatically registered
For 2. - Add instructions to _Contributing guideline_ and examples  

Implementation of proposed enhancement will be based on https://pkg.go.dev/embed

**Comment by dennwc** [comment]
Good idea! Some headers definitely need special attention and I wanted to code-generate them from Go type definitions. But you are right that quite a few files don't need it and can be added via `embed`.

**Comment by g41797** [comment]
I'll start it after defines

**Comment by g41797** [comment]
First stage : "Zero-coding" of  RegisterLibrary:

Suppose following includes were added instead of **_removed_** go files 

libs/includes/
├── AL
│   ├── alc.h
│   └── al.h
├── dirent.h
├── float.h
├── getopt.h
├── GL
│   └── gl.h
├── libgen.h
└── windows.h

During init,  RegisterLibrary will be called for all includes

Implementation will be in new reglibs.go file in root folder + test

Is it OK?
