### ISSUE TITLE
Incompatible with Go 1.23, which doesn't allow //go:linkname to internal symbols, including to runtime package

### ISSUE THREAD

**Issue by stefanb** [gotranspile/cxgo#74]
While testing Go 1.23 rc1 in 
* https://github.com/Homebrew/homebrew-core/pull/175310
 
there was an error:
````
  # github.com/gotranspile/cxgo/cmd/cxgo
  link: github.com/gotranspile/cxgo/runtime/libc: invalid reference to runtime.findnull
````

Go 1.23 no longer allows `//go:linkname * runtime.*` link instructioins, see 
* https://tip.golang.org/doc/go1.23#linker
* https://github.com/golang/go/issues/67401

It is used several times in
https://github.com/gotranspile/cxgo/blob/29871598a6a289a52f5c92cfc3da031b8aa1ce6b/runtime/libc/runtime.go

**Comment by dennwc** [comment]
Yeah, it should have happened sooner or later. Will fix it. Thank you for the early notice!

**Comment by stefanb** [comment]
Pleas don't forget to tag a release sometime before Go 1.23 is released in August.
